#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend nahese.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 471551-web-01 35.174.176.197
        server 471551-web-02 34.234.201.157
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
