#!/usr/bin/env bash
# debugging what’s keeping Ubuntu
# container’s Nginx installation from listening on port 80. 
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default 
sudo service nginx stop
sudo pkill nginx
sudo service nginx start
