#!/usr/bin/env bash
# This script displays "Best School" 10 times using with Hi at end

counter=1

while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]
    then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi

    ((counter++))
done